### ISSUE TITLE
do we handle the fatal RDMA error in our code?

### ISSUE THREAD

**Issue by gwnet** [zrlio/jNVMf#18]
hello buddy, Kernel will have below error code to do automatically recover from fatal RDMA error, make sure no resource leak at all. can you add this into this product? 

since I contribute couple of ideas. :) can you also add me as co-owner? :)

===kernel way to handle RDMA error=====
Wayne: kernel will detect RDMA error, then trigger error recovery, mark ctrl is reconnecting, and doing reset and reconnection work in one kernel work item.
static int __nvme_rdma_recv_done(struct ib_cq *cq, struct ib_wc *wc, int tag)
{

               if (unlikely(wc->status != IB_WC_SUCCESS)) {
                              nvme_rdma_wr_error(cq, wc, "RECV");
                              return 0;
               }

static void nvme_rdma_wr_error(struct ib_cq *cq, struct ib_wc *wc,
                              const char *op)
{
               struct nvme_rdma_queue *queue = cq->cq_context;
               struct nvme_rdma_ctrl *ctrl = queue->ctrl;

               if (ctrl->ctrl.state == NVME_CTRL_LIVE)
                              dev_info(ctrl->ctrl.device,
                                                   "%s for CQE 0x%p failed with status %s (%d)\n",
                                                   op, wc->wr_cqe,
                                                   ib_wc_status_msg(wc->status), wc->status);
               nvme_rdma_error_recovery(ctrl);
}

static void nvme_rdma_error_recovery(struct nvme_rdma_ctrl *ctrl)
{
               if (!nvme_change_ctrl_state(&ctrl->ctrl, NVME_CTRL_RECONNECTING))
                              return;

               queue_work(nvme_rdma_wq, &ctrl->err_work);
}

**Comment by gwnet** [comment]
May I know how it is going on?

**Comment by PepperJo** [comment]
As mentioned before, jNVMf is a low level library which forwards all the errors to the user of the API. If you need a reconnection logic you need to implement it in your application or create a wrapper library to do so. This should be very easy to do. I cannot add you as an co-owner since you have not contributed a single line of code! Feel free to open any pull request and if they look good to me I will merge them and you will be a contributor (not owner though).
